accounts/urls.py
from django.urls import path
from .views import (
UserRegistrationView,
LogoutView,
UserLoginView,
UserList,
UserDetail,
BankAccountTypeListCreateView,
BankAccountTypeRetrieveUpdateDestroyView,
UserBankAccountListCreateView,
UserBankAccountRetrieveUpdateDestroyView,
UserAddressViewSet,
UserProfileViewSet,
UserProfileView,
UserBankAccountListCreateView,
AccountSettingsView,
DeleteAccountView,
UserUpdateView,
AccountSettingsView,
    

)

app_name = 'accounts'

urlpatterns = [
path('login/', UserLoginView.as_view(), name='user_login'),
path('logout/', LogoutView.as_view(), name='user_logout'),
path('register/', UserRegistrationView.as_view(), name='user_registration'),
path('users/', UserList.as_view(), name='user_list'), 
path('users/<int:pk>', UserDetail.as_view(), name='user_detail'),
path('bank-account-types/', BankAccountTypeListCreateView.as_view(), name='bank_account_type_list_create'),
path('bank-account-types/<int:pk>', BankAccountTypeRetrieveUpdateDestroyView.as_view(), name='bank_account_type_retrieve_update_destroy'),
path('user-bank-accounts/', UserBankAccountListCreateView.as_view(), name='user_bank_account_list_create'),
path('user-bank-accounts/<int:pk>', UserBankAccountRetrieveUpdateDestroyView.as_view(), name='user_bank_account_retrieve_update_destroy'),
path('user-addresses/', UserAddressViewSet.as_view({'get': 'list', 'post': 'create'}), name='user_addresses'),
path('user-addresses/<int:pk>', UserAddressViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='user_addresses_detail'),
path('user-profiles/', UserProfileViewSet.as_view({'get': 'list', 'post': 'create'}), name='user_profiles'),
path('user-profiles/<int:pk>', UserProfileViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='user_profiles_detail'),
path('profile-settings/', UserProfileView.as_view(), name='profile_settings'),
path('create-account/', UserBankAccountListCreateView.as_view(), name='create_account'),
path('account-settings/', AccountSettingsView.as_view(), name='account_settings'),
path('delete-account/', DeleteAccountView.as_view(), name='delete_account'),
path('delete-account/', DeleteAccountView.as_view(), name='delete_account'),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from core.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('transactions/',include('transactions.urls',namespace='transactions') ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

from .models import User, BankAccountType, UserBankAccount, UserAddress,UserProfile,UserBankAccount
from .constants import GENDER_CHOICE


class UserAddressForm(forms.ModelForm):

    class Meta:
        model = UserAddress
        fields = [
            'street_address',
            'city',
            'postal_code',
            'country'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 rounded '
                    'py-3 px-4 leading-tight focus:outline-none '
                    'focus:bg-white focus:border-gray-500'
                )
            })


class UserRegistrationForm(UserCreationForm):
    account_type = forms.ModelChoiceField(
        queryset=BankAccountType.objects.all()
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICE)
    birth_date = forms.DateField()

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'phone_number',
            'password1',
            'password2',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 '
                    'rounded py-3 px-4 leading-tight '
                    'focus:outline-none focus:bg-white '
                    'focus:border-gray-500'
                )
            })

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            account_type = self.cleaned_data.get('account_type')
            gender = self.cleaned_data.get('gender')
            birth_date = self.cleaned_data.get('birth_date')

            UserBankAccount.objects.create(
                user=user,
                gender=gender,
                birth_date=birth_date,
                account_type=account_type,
                account_no=(
                    user.id +
                    settings.ACCOUNT_NUMBER_START_FROM
                )
            )
        return user

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = '__all__' 
        


 

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from rest_framework import viewsets
from django.views import View
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from rest_framework.views import APIView
from django.contrib.auth.decorators import login_required
from rest_framework.permissions import IsAuthenticated
from django.contrib.auth.views import LoginView
from django.shortcuts import HttpResponseRedirect,render,redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import generics, status
from rest_framework.response import Response
from .forms import UserRegistrationForm, UserAddressForm
from .models import BankAccountType, UserBankAccount, UserAddress, UserProfile
from .serializers import BankAccountTypeSerializer, UserBankAccountSerializer, UserSerializer,UserAddressSerializer, UserProfileSerializer
from django.contrib.auth import get_user_model

User = get_user_model()


class UserList(generics.ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer

class UserUpdateView(generics.UpdateAPIView):
    permission_classes = [IsAuthenticated]
    queryset = User.objects.all()
    serializer_class = UserSerializer
    lookup_field = 'id'

    def put(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)


class UserDeleteView(generics.DestroyAPIView):
    permission_classes = [IsAuthenticated]
    queryset = User.objects.all()
    serializer_class = UserSerializer
    lookup_field = 'id'

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)



class UserDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer



class UserRegistrationView(TemplateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'accounts/user_registration.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(reverse_lazy('transactions:transaction_report'))
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        registration_form = UserRegistrationForm(self.request.POST)
        address_form = UserAddressForm(self.request.POST)

        if registration_form.is_valid() and address_form.is_valid():
           user = registration_form.save()
           address = address_form.save(commit=False)
           address.user = user
           address.save()

           user_bank_account = UserBankAccount.objects.get(user=user) 
           messages.success(
              self.request,
                f'Thank You For Creating A Bank Account. Your Account Number is {user_bank_account.account_no}.'
            )
           return HttpResponseRedirect(reverse_lazy('transactions:deposit_money'))


        return self.render_to_response(
            self.get_context_data(
                registration_form=registration_form,
                address_form=address_form
            )
        )

    def get_context_data(self, **kwargs):
        if 'registration_form' not in kwargs:
            kwargs['registration_form'] = UserRegistrationForm()
        if 'address_form' not in kwargs:
            kwargs['address_form'] = UserAddressForm()
        return super().get_context_data(**kwargs)


class UserLoginView(LoginView):
    template_name = 'accounts/user_login.html'
    redirect_authenticated_user = False


class LogoutView(RedirectView):
    pattern_name = 'home'

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get_redirect_url(*args, **kwargs)


class BankAccountTypeListCreateView(generics.ListCreateAPIView):
    queryset = BankAccountType.objects.all()
    serializer_class = BankAccountTypeSerializer


class BankAccountTypeRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = BankAccountType.objects.all()
    serializer_class = BankAccountTypeSerializer


class UserBankAccountListCreateView(LoginRequiredMixin, generics.ListCreateAPIView):
    model = UserBankAccount
    serializer_class = UserBankAccountSerializer
    permission_classes = (IsAuthenticated,)

    def get(self, request, *args, **kwargs):
        account_types = BankAccountType.objects.all()
        context = {
            'account_types': account_types
        }
        return render(request, 'accounts/create_account.html', context=context)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class UserBankAccountRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = UserBankAccount.objects.all()
    serializer_class = UserBankAccountSerializer
    
class UserAddressViewSet(viewsets.ModelViewSet):
    queryset = UserAddress.objects.all()
    serializer_class = UserAddressSerializer



class AccountSettingsView(TemplateView):
    template_name = 'accounts/account_settings.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['account_types'] = BankAccountType.objects.all()
        context['user'] = User.objects.get(pk=self.request.user.pk)
        return context

    def post(self, request, *args, **kwargs):
        user = request.user
        account = user.account
        if 'update' in request.POST:
            account_type_name = request.POST.get('account_type')
            account_type = BankAccountType.objects.get(name=account_type_name)
            account.account_type = account_type

            account_no = request.POST.get('account_no')
            gender = request.POST.get('gender')
            birth_date = request.POST.get('birth_date')
            balance = request.POST.get('balance')
            interest_start_date = request.POST.get('interest_start_date')
            initial_deposit_date = request.POST.get('initial_deposit_date')
            account.account_type = account_type
            account.account_no = account_no
            account.gender = gender
            account.birth_date = birth_date
            account.balance = balance
            account.interest_start_date = interest_start_date
            account.initial_deposit_date = initial_deposit_date
            account.save()
            messages.success(request, 'Your account has been updated.')
            return redirect('accounts:account_settings')
        elif 'delete' in request.POST:
            account.delete()
            messages.success(request, 'Your account has been deleted.')
            return redirect('accounts:user_login')

   

class UserProfileViewSet(viewsets.ModelViewSet):
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer

class UserProfileView(View):
    template_name = 'accounts/profile_settings.html'
    
    def get(self, request):
        return render(request, self.template_name)
    
    def profile_settings(self, request):
        user = request.user
        profile = user.profile
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.save()
        context = {
            'user': user,
            'profile': profile,
        }
        return render(request, 'accounts/profile_settings.html', context)

class UserProfileDetailView(APIView):

    def get_object(self, pk):
        try:
            return UserProfile.objects.get(user=pk)
        except UserProfile.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

    def get(self, request, pk):
        profile = self.get_object(pk)
        serializer = UserProfileSerializer(profile)
        return Response(serializer.data)

    def put(self, request, pk):
        profile = self.get_object(pk)
        serializer = UserProfileSerializer(profile, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        profile = self.get_object(pk)
        profile.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)





class DeleteAccountView(View):
    def delete(self, request, *args, **kwargs):
        # burada hesap silme işlemleri yapılabilir
        return redirect('home')

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = UserProfile
    fields = ['first_name', 'last_name', 'address', 'bank_account']
    template_name = 'accounts/profile_settings.html'

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_success_url(self):
        return reverse_lazy('home')

    def form_valid(self, form):
        messages.success(self.request, 'Your profile has been updated.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'An error occurred while updating your profile.')
        return super().form_invalid(form)

    def put(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)
    

templates/accounts/account_settings.html
{% extends "core/base.html" %}

{% block content %}
{% if success %}
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4" role="alert">
    <strong class="font-bold">Success!</strong>
    <span class="block sm:inline">Your account has been updated.</span>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
        <title>Close</title>
        <path d="M14.348 5.652a.999.999 0 1 0-1.414 1.414L12.414 9l-1.652 1.652a.999.999 0 1 0 1.414 1.414L14.828 10l1.652 1.652a.997.997 0 0 0 1.414 0 .999.999 0 0 0 0-1.414L16.242 9l1.652-1.652a.999.999 0 0 0 0-1.414.999.999 0 0 0-1.414 0L14.828 8l-1.652-1.652z"/>
      </svg>
    </span>
  </div>
{% endif %}
  <h1 class="font-mono font-bold text-3xl bg-gray-200 text-center pb-5 pt-10">Account Settings</h1>
  <form method="post" class="bg-gray-300 shadow-md rounded px-8 pt-6 pb-8 mb-4" >
    {% csrf_token %}
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label for="account_type"  class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Account Type:</label>
        <select name="account_type">
          <option value="saving" {% if user.account.account_type == 'saving' %}selected{% endif %}>Saving</option>
          <option value="checking" {% if user.account.account_type == 'checking' %}selected{% endif %}>Checking</option>
        </select>
      </div>
    </div>
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label for="account_no">Account Number:</label>
      <input type="text" name="account_no" value="{{ user.account.account_no }}" readonly>
      </div>
    </div>
  
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
       
    <label for="gender">Gender:</label>
    <select name="gender">
      <option value="male" {% if user.account.gender == 'male' %}selected{% endif %}>Male</option>
      <option value="female" {% if user.account.gender == 'female' %}selected{% endif %}>Female</option>
    </select>
      </div>
    </div>
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label for="birth_date">Birth Date:</label>
        <input type="date" name="birth_date" value="{{ user.account.birth_date|date:'Y-m-d' }}">
      </div>
    </div>
    
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label for="balance">Balance:</label>
        <input type="text" name="balance" value="{{ user.account.balance }} " readonly>
      </div>
    </div>
   
    
    
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label for="initial_deposit_date">Initial Deposit Date:</label>
     <input type="date" name="initial_deposit_date" value="{{ user.account.initial_deposit_date|date:'Y-m-d' }}">
      </div>
    </div>
  
    <div class="flex items-center justify-between">
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" name="update">
        Update
      </button>
      <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit" name="delete">
        Delete
      </button>
  </div>
   
  
  </form>
  
  
{% endblock %}

templates/accounts/create_account.html
{% extends 'core/base.html' %}

{% block content %}
  <h2 class="font-mono font-bold text-3xl text-center pb-5 pt-10 bg-gray-200 ">Create a Bank Account</h2>

  <form method="POST" class="bg-gray-300 shadow-md rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div class="flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label for="account_type" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Account Type:</label>
      <select name="account_type" id="account_type">
        {% for account_type in account_types %}
          <option value="{{ account_type.id }}">{{ account_type.name }}</option>
        {% endfor %}
      </select>
      </div>
    </div>
    <div  class="flex flex-wrap -mx-3 mb-6">
      <div  class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label for="account_no" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Account Number:</label>
      <input type="number" name="account_no" id="account_no" >
      </div>
    </div>
    <div  class="flex flex-wrap -mx-3 mb-6">
     <div  class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
      <label for="gender" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Gender:</label>
      <select name="gender" id="gender">
        <option value="Male">Male</option>
        <option value="Female">Female</option>
       
      </select>
     </div>
    </div>
    <div  class="flex flex-wrap -mx-3 mb-6">
     <div  class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
      <label for="birth_date" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Birth Date:</label>
      <input type="date" name="birth_date" id="birth_date">
     </div>
    </div>
    <div  class="flex flex-wrap -mx-3 mb-6">
      <div  class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label for="balance" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Balance:</label>
      <input type="number" step="0.01" name="balance" id="balance">
      </div>
    </div>
    
    <div  class="flex flex-wrap -mx-3 mb-6">
      <div  class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label for="initial_deposit_date" class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Initial Deposit Date:</label>
      <input type="date" name="initial_deposit_date" id="initial_deposit_date">
      </div>
    </div>
    <div class="flex items-center justify-between">
      <button type="submit" class="bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Create Account</button>
      
      <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="button" name="delete" onclick="clearForm()">
        CLEAR
      </button>

    </div>
  </form>
{% endblock %}
<script>
  function clearForm() {
    document.getElementById("account_type").selectedIndex = 0;
    document.getElementById("account_no").value = "";
    document.getElementById("gender").selectedIndex = 0;
    document.getElementById("birth_date").value = "";
    document.getElementById("balance").value = "";
    document.getElementById("initial_deposit_date").value = "";
  }
  </script>

templates/accounts/profile_settings.html
{% extends "core/base.html" %}

{% block content %}
{% if success %}
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4" role="alert">
    <strong class="font-bold">Success!</strong>
    <span class="block sm:inline">Your Profile account has been updated.</span>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
        <title>Close</title>
        <path d="M14.348 5.652a.999.999 0 1 0-1.414 1.414L12.414 9l-1.652 1.652a.999.999 0 1 0 1.414 1.414L14.828 10l1.652 1.652a.997.997 0 0 0 1.414 0 .999.999 0 0 0 0-1.414L16.242 9l1.652-1.652a.999.999 0 0 0 0-1.414.999.999 0 0 0-1.414 0L14.828 8l-1.652-1.652z"/>
      </svg>
    </span>
  </div>
{% endif %}
  <h1 class="font-mono font-bold text-3xl bg-gray-200 text-center pb-5 pt-10" >Profile Settings</h1>
  <form method="post"  id="profile-form" class="bg-gray-300 shadow-md rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
   <div class='row  ' >
    <div class="col-6">
      <div class="form-group flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label for="first_name"  class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">First Name:</label>
          <input type="text" name="first_name" id="first_name" class="form-control w-full rounded-md border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 hover:border-gray-400" value="{{ user.first_name }}">  
        </div>
      </div>
    </div>

    <div class="col-6">
      
      <div class="form-group flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="last_name">Last Name:</label>
        <input type="text" name="last_name" id="last_name" class="form-control w-full rounded-md border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 hover:border-gray-400" value="{{ user.last_name }}">
        </div>
    </div>

   </div>
      <div class="form-group flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="address">Phone Number:</label>
          <input type="text" name="phone_number" id="phone_number" class="form-control w-full rounded-md border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 hover:border-gray-400" value="{{ user.phone_number }}">
        </div>
    </div>
    
    <div class="form-group flex flex-wrap -mx-3 mb-6">
      <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="bank_account">Bank Account:</label>
        <input type="text" name="bank_account" id="bank_account" class="form-control w-full rounded-md border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 hover:border-gray-400" value="{{ user.account.account_no }}" readonly>
      </div>
      
    </div>
    <div class="row">
      <div class="col-6">
        <div class="form-group flex flex-wrap -mx-3 mb-6">
          <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
            <label  class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"for="address">Country:</label>
            <input type="text" name="address" id="address" class="form-control w-full rounded-md border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 hover:border-gray-400" value="{{ user.address.country }}">
    
          </div>
          
      </div>
      <div class="col-6">
        <div class="form-group flex flex-wrap -mx-3 mb-6">
          <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="address">City:</label>
            <input type="text" name="address" id="address" class="form-control w-full rounded-md border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 hover:border-gray-400" value="{{ user.address.city }}">
          </div>
        
      </div>
      </div>
    </div>
    <div class="col-6">
      <div class="form-group flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
          <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="address">Street Address:</label>
          <input type="text" name="address" id="address" class="form-control w-full rounded-md border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 hover:border-gray-400" value="{{ user.address.street_address }}">
        </div>
      
    </div>
    </div>
  </div>
    <div class="flex items-center justify-between">
      {% comment %} <button type="submit"  class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Save Changes</button> {% endcomment %}
   
    </div>
  </form>
{% endblock %}

{% block script %}
<script>
$(document).ready(function() {
  // Delete Account Button
  $('#delete-btn').click(function() {
    if (confirm("Are you sure you want to delete your account? This action cannot be undone.")) {
      $.ajax({
        url: "{% url 'accounts:delete_account' %}",
        type: "DELETE",
        success: function(response) {
          alert("Your account has been deleted.");
          window.location.href = "{% url 'home' %}";
        },
        error: function(response) {
          alert("An error occurred while deleting your account.");
        }
      });
    }
  });

  // Fill form with user data
  var user = JSON.parse('{{ user_json|escapejs }}');
  $('#first_name').val(user.first_name);
  $('#last_name').val(user.last_name);
  $('#bank_account').val(user.account.account_no);
  $('#address').val(user.address.street_address);

  // PUT Request on form submit
  $(document).ready(function() {
    // PUT Request on form submit
    $('#profile-form').submit(function(e) {
      e.preventDefault();
      $.ajax({
        url: "{% url 'accounts:user_update' %}",
        type: "POST",
        data: $(this).serialize(),
        success: function(response) {
          alert("Profiliniz güncellendi.");
        },
        error: function(response) {
          alert("Profil güncelleme işlemi sırasında bir hata oluştu.");
        }
      });
    });
  });
  
});
</script>
{% endblock %}