accounts/urls.py
from django.urls import path
from .views import (
UserRegistrationView,
LogoutView,
UserLoginView,
UserList,
UserDetail,
BankAccountTypeListCreateView,
BankAccountTypeRetrieveUpdateDestroyView,
UserBankAccountListCreateView,
UserBankAccountRetrieveUpdateDestroyView,
UserAddressViewSet,
UserProfileViewSet,
UserProfileView,
UserBankAccountListCreateView,
AccountSettingsView,
DeleteAccountView,
UserUpdateView,
AccountSettingsView,
    

)

app_name = 'accounts'

urlpatterns = [
path('login/', UserLoginView.as_view(), name='user_login'),
path('logout/', LogoutView.as_view(), name='user_logout'),
path('register/', UserRegistrationView.as_view(), name='user_registration'),
path('users/', UserList.as_view(), name='user_list'), 
path('users/<int:pk>', UserDetail.as_view(), name='user_detail'),
path('bank-account-types/', BankAccountTypeListCreateView.as_view(), name='bank_account_type_list_create'),
path('bank-account-types/<int:pk>', BankAccountTypeRetrieveUpdateDestroyView.as_view(), name='bank_account_type_retrieve_update_destroy'),
path('user-bank-accounts/', UserBankAccountListCreateView.as_view(), name='user_bank_account_list_create'),
path('user-bank-accounts/<int:pk>', UserBankAccountRetrieveUpdateDestroyView.as_view(), name='user_bank_account_retrieve_update_destroy'),
path('user-addresses/', UserAddressViewSet.as_view({'get': 'list', 'post': 'create'}), name='user_addresses'),
path('user-addresses/<int:pk>', UserAddressViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='user_addresses_detail'),
path('user-profiles/', UserProfileViewSet.as_view({'get': 'list', 'post': 'create'}), name='user_profiles'),
path('user-profiles/<int:pk>', UserProfileViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}), name='user_profiles_detail'),
path('profile-settings/', UserProfileView.as_view(), name='profile_settings'),
path('create-account/', UserBankAccountListCreateView.as_view(), name='create_account'),
path('account-settings/', AccountSettingsView.as_view(), name='account_settings'),
path('delete-account/', DeleteAccountView.as_view(), name='delete_account'),
path('delete-account/', DeleteAccountView.as_view(), name='delete_account'),
]

banking_system/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from core.views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('transactions/',include('transactions.urls',namespace='transactions') ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path

from .views import DepositMoneyView, WithdrawMoneyView, TransactionRepostView


app_name = 'transactions'


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
]

transactions/models.py
from django.db import models

from .constants import TRANSACTION_TYPE_CHOICES
from accounts.models import UserBankAccount


class Transaction(models.Model):
    account = models.ForeignKey(
        UserBankAccount,
        related_name='transactions',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    balance_after_transaction = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    transaction_type = models.PositiveSmallIntegerField(
        choices=TRANSACTION_TYPE_CHOICES
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.account.user.username}-- {self.account.account_no}     "

    class Meta:
        ordering = ['timestamp']

transactions/forms.py
import datetime

from django import forms
from django.conf import settings

from .models import Transaction


class TransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = [
            'amount',
            'transaction_type'
        ]

    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account')
        super().__init__(*args, **kwargs)

        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.account = self.account
        self.instance.balance_after_transaction = self.account.balance
        return super().save()


class DepositForm(TransactionForm):

    def clean_amount(self):
        min_deposit_amount = settings.MINIMUM_DEPOSIT_AMOUNT
        amount = self.cleaned_data.get('amount')

        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f'You need to deposit at least {min_deposit_amount} $'
            )

        return amount


class WithdrawForm(TransactionForm):

    def clean_amount(self):
        account = self.account
        min_withdraw_amount = settings.MINIMUM_WITHDRAWAL_AMOUNT
        max_withdraw_amount = (
            account.account_type.maximum_withdrawal_amount
        )
        balance = account.balance

        amount = self.cleaned_data.get('amount')

        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at least {min_withdraw_amount} $'
            )

        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at most {max_withdraw_amount} $'
            )

        if amount > balance:
            raise forms.ValidationError(
                f'You have {balance} $ in your account. '
                'You can not withdraw more than your account balance'
            )

        return amount


class TransactionDateRangeForm(forms.Form):
    daterange = forms.CharField(required=False)
    min_amount = forms.ChoiceField (required=False)
    max_amount = forms.ChoiceField (required=False)

    def clean_daterange(self):
        daterange = self.cleaned_data.get("daterange")
        print(daterange)

        try:
            daterange = daterange.split(' - ')
            print(daterange)
            if len(daterange) == 2:
                for date in daterange:
                    datetime.datetime.strptime(date, '%Y-%m-%d')
                return daterange
            else:
                raise forms.ValidationError("Please select a date range.")
        except (ValueError, AttributeError):
            raise forms.ValidationError("Invalid date range")

    def clean(self):
        cleaned_data = super().clean()
        min_amount = cleaned_data.get('min_amount')
        max_amount = cleaned_data.get('max_amount')

        if min_amount is not None and max_amount is not None and min_amount > max_amount:
            raise forms.ValidationError('The minimum amount must be less than or equal to the maximum amount.')

        return cleaned_data

# forms.py

class TransactionFilter(forms.Form):
    filter = forms.ChoiceField(choices=(('', 'Select Filter'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'),('amount','amount')))

transactions/views.py
from dateutil.relativedelta import relativedelta

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, ListView
import datetime
from transactions.constants import DEPOSIT, WITHDRAWAL
from transactions.forms import (
    DepositForm,
    TransactionDateRangeForm,
    WithdrawForm,
)
from transactions.models import Transaction


class TransactionRepostView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_report.html'
    model = Transaction
    form_data = {}

    def get(self, request, *args, **kwargs):
        form = TransactionDateRangeForm(request.GET or None)
        if form.is_valid():
            self.form_data = form.cleaned_data

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        filter_type = self.request.GET.get('filter')
        queryset = queryset.filter(account__user=self.request.user)
        if filter_type == 'date':
           daterange = self.request.GET.get('daterange')
           if daterange:
            dates = daterange.split(" - ")
            if len(dates) == 2:
                start_date = datetime.datetime.strptime(dates[0], '%Y-%m-%d').date()
                end_date = datetime.datetime.strptime(dates[1], '%Y-%m-%d').date() + datetime.timedelta(days=1)
                queryset = queryset.filter(timestamp__range=[start_date, end_date], account__user=self.request.user)
            else:
                messages.warning(self.request, "Please enter a valid date range.")
        elif filter_type == 'deposit':
          queryset = queryset.filter(transaction_type=1, account__user=self.request.user)
        elif filter_type == 'withdraw':
          queryset = queryset.filter(transaction_type=2, account__user=self.request.user)
        elif filter_type == 'amount':
            queryset = queryset.filter(transaction_type=3, account__user=self.request.user, amount__lt=0)
        else:
          queryset = queryset.filter(account__user=self.request.user)
        return queryset



    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        account = self.request.user.account
        transactions = context['object_list']
        final_balance = account.balance
        for transaction in transactions:
            if transaction.transaction_type == DEPOSIT:
                final_balance += transaction.amount
            elif transaction.transaction_type == WITHDRAWAL:
                final_balance -= transaction.amount

            transaction.balance_after_transaction = final_balance

        context['account'] = account
        context['final_balance'] = final_balance
        context['form'] = TransactionDateRangeForm(initial=self.form_data)
        return context


class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'transactions/transaction_form.html'
    model = Transaction
    title = ''
    success_url = reverse_lazy('transactions:transaction_report')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account': self.request.user.account
        })
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': self.title
        })

        return context


class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposit Money to Your Account'

    def get_initial(self):
        initial = {'transaction_type': DEPOSIT}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account

        if not account.initial_deposit_date:
            now = timezone.now()
            
            account.initial_deposit_date = now
            

        account.balance += amount
        account.save(
            update_fields=[
                'initial_deposit_date',
                'balance',
               
            ]
        )

        messages.success(
            self.request,
            f'{amount}$ was deposited to your account successfully'
        )

        return super().form_valid(form)


class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw Money from Your Account'

    def get_initial(self):
        initial = {'transaction_type': WITHDRAWAL}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')

        self.request.user.account.balance -= form.cleaned_data.get('amount')
        self.request.user.account.save(update_fields=['balance'])

        messages.success(
            self.request,
            f'Successfully withdrawn {amount}$ from your account'
        )

        return super().form_valid(form)

templates/transactions/transaction_form.html
{% extends 'core/base.html' %}

{% block head_title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">{{ title }}</h1>
<hr />
<div class="w-full mt-5">
    <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                Amount
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
        </div>
        {% if form.amount.errors %}
            {% for error in form.amount.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %}
        {% endif %}
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            Submit
        </button>
    </form>
</div>
{% endblock %}

templates/transactions/transaction_report.html
{% extends 'core/base.html' %}

{% block head_title %}Transaction Report{% endblock %}

{% block head_extra %}
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{% endblock %}

{% block content %}
<h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Transaction Report</h1>
<hr />
<form method="get">
    <div class="mt-10 h-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative">
        <input type="search" name="daterange" id="search" placeholder="Filter using date range" value="{{ request.GET.daterange }}" class="appearance-none w-full outline-none focus:outline-none active:outline-none" />
        <select name="filter" id="filter" class="ml-2 border rounded-md">
            <option value="">Select Filter</option>
            <option value="date"{% if request.GET.filter == 'date' %} selected="selected"{% endif %}>Date</option>
            <option value="deposit"{% if request.GET.filter == 'deposit' %} selected="selected"{% endif %}>Deposit</option>
            <option value="withdraw"{% if request.GET.filter == 'withdraw' %} selected="selected"{% endif %}>Withdraw</option>
            {% comment %} <option value="amount"{% if request.GET.filter == 'amount' %} selected="selected"{% endif %}>Amount</option> {% endcomment %}
        </select>
        <button type="submit" class="ml-2 border rounded-md px-3 py-1 bg-green-500 text-white font-semibold hover:bg-green-600">Filter</button>
    </div>
    {% if form.daterange.errors %}
        {% for error in form.daterange.errors %}
            <p class="text-red-600 text-sm italic">{{ error }}</p>
        {% endfor %}
    {% endif %}
</form>

<table class="table-auto mx-auto w-full mt-8">
<thead class="bg-green-500 text-white">
<tr class="uppercase font-semibold text-sm">
<th class="px-4 py-2">Transaction Type</th>
<th class="px-4 py-2">Date</th>
<th class="px-4 py-2">Amount</th>
<th class="px-4 py-2">Balance After Transaction</th>
</tr>
</thead>
<tbody>
{% for transaction in object_list %}
<tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
<td class="border px-4 py-2 text-center">{{ transaction.get_transaction_type_display }}</td>
<td class="border px-4 py-2 text-center">{{ transaction.timestamp }}</td>
<td class="border px-4 py-2 text-center">$ {{ transaction.amount }}</td>
<td class="border px-4 py-2 text-center">$ {{ transaction.balance_after_transaction }}</td>
</tr>
{% endfor %}
<tr class="bg-green-500 text-white">
<th class="px-4 py-2 text-right" colspan="3">Final Balance</th>
<th class="px-4 py-2 text-center">$ {{ account.balance }}</th>
</tr>
</tbody>
</table>




{% if is_paginated %}
  <div class="pagination text-center text-white bg-green-500 mt-1 p-4 ">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current-page">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>
{% endif %}




{% endblock %}



{% block footer_extra %}
    <script type="text/javascript">
        $(function () {
            $('input[name="daterange"]').daterangepicker({
                autoUpdateInput: false,
                locale: {
                    cancelLabel: "Clear",
                },
            });

            $('input[name="daterange"]').on("apply.daterangepicker", function (ev, picker) {
                $(this).val(picker.startDate.format("YYYY-MM-DD") + " - " + picker.endDate.format("YYYY-MM-DD"));
            });

            $('input[name="daterange"]').on("cancel.daterangepicker", function (ev, picker) {
                $(this).val("");
            });
        });
    </script>
{% endblock %}